# Generated by Django 4.0.5 on 2022-07-07 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
