# Generated by Django 4.0.5 on 2022-07-07 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_category_orders'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
    ]
